const express = require('express');
const router = express.Router();
const { uploadReceipt, getReceipt, listReceipts } = require('../controllers/receipts');
const auth = require('../utils/auth');
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });
router.post('/upload', auth, upload.single('receipt'), uploadReceipt);
router.get('/:id', auth, getReceipt);
router.get('/', auth, listReceipts);
module.exports = router;
